# Generated by Django 3.2.4 on 2021-06-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('fundacja', 'fundacja'), ('organizacja_pozarzadowa', 'organizacja_pozarzadowa'), ('zbiorka_lokalna', 'zbiorka_lokalna')], default='fundacja', max_length=64, null=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
