# Generated by Django 3.2.4 on 2021-06-22 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=16)),
                ('pick_up_date', models.DateField(null=True)),
                ('pick_up_time', models.TimeField(null=True)),
                ('pick_up_comment', models.TextField(null=True)),
                ('categories', models.ManyToManyField(to='main.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institution')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
